[51/safe-env-indicator-in-header] CSS, add env in header's data-attrs.
CapSens/light_admin pull request #37
Opened 2023-05-26 07:41 UTC by Kernael

https://trello.com/c/ebvmZY9I/51-indicateur-denvironnement-safe-dans-le-header

2023-05-26 07:41 UTC, Kernael commented
Je vois que le build fail depuis un certain temps 👀 Est-ce-qu'on veut mettre à jour les gems ?

2023-05-26 07:52 UTC, virginie-perrichon requested changes

2023-05-26 07:52 UTC, virginie-perrichon commented on CHANGELOG.md
> +* Add a green border to the header so we can now when we are in a safe environment (staging, development).
`we can know` no ?

2023-05-26 08:09 UTC, virginie-perrichon commented
Good pour moi @AntoineBecquet je te laisse la partie Back :)

2023-05-26 08:15 UTC, Kernael commented on CHANGELOG.md
> +* Add a green border to the header so we can now when we are in a safe environment (staging, development).
Bien vu !

2023-05-26 16:20 UTC, AntoineBecquet approved these changes

2023-05-26 16:21 UTC, AntoineBecquet commented
> Good pour moi @AntoineBecquet je te laisse la partie Back :)

@virginie-perrichon approuve la PR alors, sinon github râle !

2023-05-29 07:12 UTC, virginie-perrichon approved these changes

2023-05-31 08:07 UTC, merged

2023-05-31 08:40 UTC, AntoineBecquet commented
@Kernael c'est release